### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by QuingKhaos** [bytepark/SuluEventBundle#1]
Hi, I would like to ask if you still maintain this bundle?

**Comment by fbatschi** [comment]
Depends on what you mean by maintained. Currently we have no new releases planned. The repo is kinda meant as an example on how to do a bundle for event management.

Anything you miss or any bugs you've found? Simply open an issue with description or send in a pull request!

**Comment by QuingKhaos** [comment]
It depends on the develop branch of Sulu and is not installable from packagist because the package name is `sulu/event-bundle` and even the PHP namespace of Sulu itself is captured :grin: 

And it seemed incompatible with the current release of Sulu. But already forked it, as you said, it's a perfect example to create our own bundle :sweat_smile:
